//
// Created by ha028653 on 12/14/2023.
//

#ifndef GRAPH_PUZZLE_GAME_HALENURARPACIK_MAIN_H
#define GRAPH_PUZZLE_GAME_HALENURARPACIK_MAIN_H


class Main {

};


#endif //GRAPH_PUZZLE_GAME_HALENURARPACIK_MAIN_H
